

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1050, 730)
        Dialog.setAutoFillBackground(True)
        self.stackedWidget = QtWidgets.QStackedWidget(Dialog)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 20, 1051, 711))
        self.stackedWidget.setMaximumSize(QtCore.QSize(1051, 711))
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(200, 60, 631, 71))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.page)
        self.pushButton.setGeometry(QtCore.QRect(100, 390, 261, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.page)
        self.pushButton_2.setGeometry(QtCore.QRect(350, 550, 261, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.page)
        self.pushButton_3.setGeometry(QtCore.QRect(640, 460, 261, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.line = QtWidgets.QFrame(self.page)
        self.line.setGeometry(QtCore.QRect(210, 120, 20, 271))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.page)
        self.line_2.setGeometry(QtCore.QRect(460, 110, 20, 441))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.page)
        self.line_3.setGeometry(QtCore.QRect(750, 110, 20, 351))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.stackedWidget.addWidget(self.page)
        self.page_24 = QtWidgets.QWidget()
        self.page_24.setObjectName("page_24")
        self.label_2 = QtWidgets.QLabel(self.page_24)
        self.label_2.setGeometry(QtCore.QRect(380, 50, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.page_24)
        self.label_3.setGeometry(QtCore.QRect(260, 240, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.page_24)
        self.label_4.setGeometry(QtCore.QRect(260, 310, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.page_24)
        self.plainTextEdit.setGeometry(QtCore.QRect(380, 240, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.page_24)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(380, 310, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.plainTextEdit_2.setFont(font)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.page_24)
        self.pushButton_4.setGeometry(QtCore.QRect(380, 400, 261, 61))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.stackedWidget.addWidget(self.page_24)
        self.page_10 = QtWidgets.QWidget()
        self.page_10.setObjectName("page_10")
        self.label_5 = QtWidgets.QLabel(self.page_10)
        self.label_5.setGeometry(QtCore.QRect(350, 20, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.line_29 = QtWidgets.QFrame(self.page_10)
        self.line_29.setGeometry(QtCore.QRect(0, 60, 1051, 16))
        self.line_29.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_29.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_29.setObjectName("line_29")
        self.stackedWidget.addWidget(self.page_10)
        self.page_11 = QtWidgets.QWidget()
        self.page_11.setObjectName("page_11")
        self.label_6 = QtWidgets.QLabel(self.page_11)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.pushButton_5 = QtWidgets.QPushButton(self.page_11)
        self.pushButton_5.setGeometry(QtCore.QRect(120, 320, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.page_11)
        self.pushButton_6.setGeometry(QtCore.QRect(360, 520, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.page_11)
        self.pushButton_7.setGeometry(QtCore.QRect(510, 200, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.line_4 = QtWidgets.QFrame(self.page_11)
        self.line_4.setGeometry(QtCore.QRect(200, 0, 20, 321))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.page_11)
        self.line_5.setGeometry(QtCore.QRect(450, 10, 20, 511))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.page_11)
        self.line_6.setGeometry(QtCore.QRect(610, -80, 20, 281))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.pushButton_8 = QtWidgets.QPushButton(self.page_11)
        self.pushButton_8.setGeometry(QtCore.QRect(690, 420, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.line_7 = QtWidgets.QFrame(self.page_11)
        self.line_7.setGeometry(QtCore.QRect(790, -20, 20, 441))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_28 = QtWidgets.QFrame(self.page_11)
        self.line_28.setGeometry(QtCore.QRect(0, 30, 1051, 16))
        self.line_28.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_28.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_28.setObjectName("line_28")
        self.stackedWidget.addWidget(self.page_11)
        self.page_12 = QtWidgets.QWidget()
        self.page_12.setObjectName("page_12")
        self.label_7 = QtWidgets.QLabel(self.page_12)
        self.label_7.setGeometry(QtCore.QRect(10, 20, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.page_12)
        self.label_8.setGeometry(QtCore.QRect(360, 300, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.page_12)
        self.label_9.setGeometry(QtCore.QRect(360, 390, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.page_12)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(490, 300, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.plainTextEdit_3.setFont(font)
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(self.page_12)
        self.plainTextEdit_4.setGeometry(QtCore.QRect(490, 390, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.plainTextEdit_4.setFont(font)
        self.plainTextEdit_4.setTabletTracking(False)
        self.plainTextEdit_4.setPlainText("")
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.pushButton_9 = QtWidgets.QPushButton(self.page_12)
        self.pushButton_9.setGeometry(QtCore.QRect(480, 510, 271, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_10 = QtWidgets.QLabel(self.page_12)
        self.label_10.setGeometry(QtCore.QRect(370, 630, 461, 31))
        font = QtGui.QFont()
        font.setFamily("NSimSun")
        font.setPointSize(15)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.line_27 = QtWidgets.QFrame(self.page_12)
        self.line_27.setGeometry(QtCore.QRect(0, 50, 1051, 16))
        self.line_27.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_27.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_27.setObjectName("line_27")
        self.stackedWidget.addWidget(self.page_12)
        self.page_13 = QtWidgets.QWidget()
        self.page_13.setObjectName("page_13")
        self.label_11 = QtWidgets.QLabel(self.page_13)
        self.label_11.setGeometry(QtCore.QRect(30, 10, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.page_13)
        self.label_12.setGeometry(QtCore.QRect(150, 100, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.page_13)
        self.label_13.setGeometry(QtCore.QRect(150, 150, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.page_13)
        self.label_14.setGeometry(QtCore.QRect(150, 200, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.page_13)
        self.label_15.setGeometry(QtCore.QRect(150, 270, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.page_13)
        self.label_16.setGeometry(QtCore.QRect(150, 320, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.page_13)
        self.label_17.setGeometry(QtCore.QRect(150, 370, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.page_13)
        self.label_18.setGeometry(QtCore.QRect(150, 420, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.page_13)
        self.label_19.setGeometry(QtCore.QRect(150, 470, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.page_13)
        self.label_20.setGeometry(QtCore.QRect(150, 520, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.line_10 = QtWidgets.QFrame(self.page_13)
        self.line_10.setGeometry(QtCore.QRect(0, 40, 1061, 16))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.plainTextEdit_5 = QtWidgets.QPlainTextEdit(self.page_13)
        self.plainTextEdit_5.setGeometry(QtCore.QRect(260, 100, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plainTextEdit_5.setFont(font)
        self.plainTextEdit_5.setObjectName("plainTextEdit_5")
        self.plainTextEdit_6 = QtWidgets.QPlainTextEdit(self.page_13)
        self.plainTextEdit_6.setGeometry(QtCore.QRect(260, 150, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plainTextEdit_6.setFont(font)
        self.plainTextEdit_6.setObjectName("plainTextEdit_6")
        self.plainTextEdit_7 = QtWidgets.QPlainTextEdit(self.page_13)
        self.plainTextEdit_7.setGeometry(QtCore.QRect(260, 200, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plainTextEdit_7.setFont(font)
        self.plainTextEdit_7.setObjectName("plainTextEdit_7")
        self.plainTextEdit_8 = QtWidgets.QPlainTextEdit(self.page_13)
        self.plainTextEdit_8.setGeometry(QtCore.QRect(260, 260, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plainTextEdit_8.setFont(font)
        self.plainTextEdit_8.setObjectName("plainTextEdit_8")
        self.plainTextEdit_9 = QtWidgets.QPlainTextEdit(self.page_13)
        self.plainTextEdit_9.setGeometry(QtCore.QRect(260, 310, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plainTextEdit_9.setFont(font)
        self.plainTextEdit_9.setObjectName("plainTextEdit_9")
        self.plainTextEdit_10 = QtWidgets.QPlainTextEdit(self.page_13)
        self.plainTextEdit_10.setGeometry(QtCore.QRect(260, 360, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plainTextEdit_10.setFont(font)
        self.plainTextEdit_10.setObjectName("plainTextEdit_10")
        self.plainTextEdit_11 = QtWidgets.QPlainTextEdit(self.page_13)
        self.plainTextEdit_11.setGeometry(QtCore.QRect(260, 410, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plainTextEdit_11.setFont(font)
        self.plainTextEdit_11.setObjectName("plainTextEdit_11")
        self.plainTextEdit_12 = QtWidgets.QPlainTextEdit(self.page_13)
        self.plainTextEdit_12.setGeometry(QtCore.QRect(260, 460, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plainTextEdit_12.setFont(font)
        self.plainTextEdit_12.setObjectName("plainTextEdit_12")
        self.plainTextEdit_13 = QtWidgets.QPlainTextEdit(self.page_13)
        self.plainTextEdit_13.setGeometry(QtCore.QRect(260, 510, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plainTextEdit_13.setFont(font)
        self.plainTextEdit_13.setObjectName("plainTextEdit_13")
        self.pushButton_10 = QtWidgets.QPushButton(self.page_13)
        self.pushButton_10.setGeometry(QtCore.QRect(730, 600, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.page_13)
        self.pushButton_11.setGeometry(QtCore.QRect(270, 600, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setObjectName("pushButton_11")
        self.plainTextEdit_14 = QtWidgets.QPlainTextEdit(self.page_13)
        self.plainTextEdit_14.setGeometry(QtCore.QRect(720, 200, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.plainTextEdit_14.setFont(font)
        self.plainTextEdit_14.setObjectName("plainTextEdit_14")
        self.line_8 = QtWidgets.QFrame(self.page_13)
        self.line_8.setGeometry(QtCore.QRect(610, 320, 20, 301))
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(self.page_13)
        self.line_9.setGeometry(QtCore.QRect(500, 620, 118, 3))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.pushButton_12 = QtWidgets.QPushButton(self.page_13)
        self.pushButton_12.setGeometry(QtCore.QRect(720, 300, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setObjectName("pushButton_12")
        self.line_11 = QtWidgets.QFrame(self.page_13)
        self.line_11.setGeometry(QtCore.QRect(620, 310, 101, 16))
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.line_12 = QtWidgets.QFrame(self.page_13)
        self.line_12.setGeometry(QtCore.QRect(820, 340, 20, 261))
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.stackedWidget.addWidget(self.page_13)
        self.page_14 = QtWidgets.QWidget()
        self.page_14.setObjectName("page_14")
        self.label_21 = QtWidgets.QLabel(self.page_14)
        self.label_21.setGeometry(QtCore.QRect(10, 10, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.pushButton_13 = QtWidgets.QPushButton(self.page_14)
        self.pushButton_13.setGeometry(QtCore.QRect(680, 150, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.page_14)
        self.pushButton_14.setGeometry(QtCore.QRect(680, 260, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.page_14)
        self.pushButton_15.setGeometry(QtCore.QRect(680, 370, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.page_14)
        self.pushButton_16.setGeometry(QtCore.QRect(680, 490, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setObjectName("pushButton_16")
        self.label_22 = QtWidgets.QLabel(self.page_14)
        self.label_22.setGeometry(QtCore.QRect(130, 290, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.page_14)
        self.label_23.setGeometry(QtCore.QRect(240, 290, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.page_14)
        self.label_24.setGeometry(QtCore.QRect(110, 380, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.label_49 = QtWidgets.QLabel(self.page_14)
        self.label_49.setGeometry(QtCore.QRect(100, 470, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.line_26 = QtWidgets.QFrame(self.page_14)
        self.line_26.setGeometry(QtCore.QRect(0, 40, 1051, 16))
        self.line_26.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_26.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_26.setObjectName("line_26")
        self.stackedWidget.addWidget(self.page_14)
        self.page_15 = QtWidgets.QWidget()
        self.page_15.setObjectName("page_15")
        self.label_50 = QtWidgets.QLabel(self.page_15)
        self.label_50.setGeometry(QtCore.QRect(10, 0, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.pushButton_33 = QtWidgets.QPushButton(self.page_15)
        self.pushButton_33.setGeometry(QtCore.QRect(150, 270, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_33.setFont(font)
        self.pushButton_33.setObjectName("pushButton_33")
        self.line_25 = QtWidgets.QFrame(self.page_15)
        self.line_25.setGeometry(QtCore.QRect(0, 30, 1051, 16))
        self.line_25.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_25.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_25.setObjectName("line_25")
        self.pushButton_34 = QtWidgets.QPushButton(self.page_15)
        self.pushButton_34.setGeometry(QtCore.QRect(690, 280, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_34.setFont(font)
        self.pushButton_34.setObjectName("pushButton_34")
        self.pushButton_35 = QtWidgets.QPushButton(self.page_15)
        self.pushButton_35.setGeometry(QtCore.QRect(160, 620, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_35.setFont(font)
        self.pushButton_35.setObjectName("pushButton_35")
        self.pushButton_36 = QtWidgets.QPushButton(self.page_15)
        self.pushButton_36.setGeometry(QtCore.QRect(690, 620, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_36.setFont(font)
        self.pushButton_36.setObjectName("pushButton_36")
        self.label_51 = QtWidgets.QLabel(self.page_15)
        self.label_51.setGeometry(QtCore.QRect(650, 580, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_51.setFont(font)
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(self.page_15)
        self.label_52.setGeometry(QtCore.QRect(140, 580, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QLabel(self.page_15)
        self.label_53.setGeometry(QtCore.QRect(160, 230, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.label_54 = QtWidgets.QLabel(self.page_15)
        self.label_54.setGeometry(QtCore.QRect(730, 240, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.label_55 = QtWidgets.QLabel(self.page_15)
        self.label_55.setGeometry(QtCore.QRect(150, 50, 231, 181))
        self.label_55.setAutoFillBackground(False)
        self.label_55.setStyleSheet("background-image: url(:/newPrefix/2.-vidnyan---tantradnyan-31.-khanolkar-vasant-ramji_1.jpg);")
        self.label_55.setText("")
        self.label_55.setPixmap(QtGui.QPixmap(":/newPrefix/2.-vidnyan---tantradnyan-31.-khanolkar-vasant-ramji_1.jpg"))
        self.label_55.setScaledContents(True)
        self.label_55.setObjectName("label_55")
        self.label_56 = QtWidgets.QLabel(self.page_15)
        self.label_56.setGeometry(QtCore.QRect(700, 60, 161, 161))
        self.label_56.setStyleSheet("background-image: url(:/newPrefix/EqIZ5uZUYAE1dxU.jpg);")
        self.label_56.setText("")
        self.label_56.setPixmap(QtGui.QPixmap(":/newPrefix/EqIZ5uZUYAE1dxU.jpg"))
        self.label_56.setScaledContents(True)
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QLabel(self.page_15)
        self.label_57.setGeometry(QtCore.QRect(170, 370, 191, 181))
        self.label_57.setAutoFillBackground(False)
        self.label_57.setStyleSheet("background-image: url(:/newPrefix/2.-vidnyan---tantradnyan-31.-khanolkar-vasant-ramji_1.jpg);")
        self.label_57.setText("")
        self.label_57.setPixmap(QtGui.QPixmap(":/newPrefix/Dr._Kotnis.jpg"))
        self.label_57.setScaledContents(True)
        self.label_57.setObjectName("label_57")
        self.label_58 = QtWidgets.QLabel(self.page_15)
        self.label_58.setGeometry(QtCore.QRect(650, 380, 301, 201))
        self.label_58.setAutoFillBackground(False)
        self.label_58.setStyleSheet("background-image: url(:/newPrefix/2.-vidnyan---tantradnyan-31.-khanolkar-vasant-ramji_1.jpg);")
        self.label_58.setText("")
        self.label_58.setPixmap(QtGui.QPixmap(":/newPrefix/anandi-2.jpg"))
        self.label_58.setScaledContents(True)
        self.label_58.setObjectName("label_58")
        self.stackedWidget.addWidget(self.page_15)
        self.page_16 = QtWidgets.QWidget()
        self.page_16.setObjectName("page_16")
        self.label_59 = QtWidgets.QLabel(self.page_16)
        self.label_59.setGeometry(QtCore.QRect(20, 20, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_59.setFont(font)
        self.label_59.setObjectName("label_59")
        self.stackedWidget.addWidget(self.page_16)
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setObjectName("page_9")
        self.label_60 = QtWidgets.QLabel(self.page_9)
        self.label_60.setGeometry(QtCore.QRect(20, 20, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_60.setFont(font)
        self.label_60.setObjectName("label_60")
        self.stackedWidget.addWidget(self.page_9)
        self.page_17 = QtWidgets.QWidget()
        self.page_17.setObjectName("page_17")
        self.stackedWidget.addWidget(self.page_17)
        self.page_18 = QtWidgets.QWidget()
        self.page_18.setObjectName("page_18")
        self.stackedWidget.addWidget(self.page_18)
        self.page_19 = QtWidgets.QWidget()
        self.page_19.setObjectName("page_19")
        self.stackedWidget.addWidget(self.page_19)
        self.page_20 = QtWidgets.QWidget()
        self.page_20.setObjectName("page_20")
        self.stackedWidget.addWidget(self.page_20)
        self.page_21 = QtWidgets.QWidget()
        self.page_21.setObjectName("page_21")
        self.stackedWidget.addWidget(self.page_21)
        self.page_22 = QtWidgets.QWidget()
        self.page_22.setObjectName("page_22")
        self.stackedWidget.addWidget(self.page_22)
        self.page_23 = QtWidgets.QWidget()
        self.page_23.setObjectName("page_23")
        self.stackedWidget.addWidget(self.page_23)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.stackedWidget.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.stackedWidget.addWidget(self.page_7)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.stackedWidget.addWidget(self.page_8)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:28pt; color:#00ff00;\">APSIT CLINIC MANAGMENT SYSTEM</span></p></body></html>"))
        self.pushButton.setText(_translate("Dialog", "ADMIN"))
        self.pushButton_2.setText(_translate("Dialog", "PATEINT"))
        self.pushButton_3.setText(_translate("Dialog", "DOCTOR"))
        self.label_2.setText(_translate("Dialog", "ADMIN LOGIN"))
        self.label_3.setText(_translate("Dialog", "userid"))
        self.label_4.setText(_translate("Dialog", "password"))
        self.pushButton_4.setText(_translate("Dialog", "LOGIN"))
        self.label_5.setText(_translate("Dialog", "ADMIN DASHBORD"))
        self.label_6.setText(_translate("Dialog", "PATIENT"))
        self.pushButton_5.setText(_translate("Dialog", "BOOK APPOINT"))
        self.pushButton_6.setText(_translate("Dialog", "REGISTER"))
        self.pushButton_7.setText(_translate("Dialog", "LOGIN"))
        self.pushButton_8.setText(_translate("Dialog", "DOCTORS DETAILS"))
        self.label_7.setText(_translate("Dialog", "PATIENT LOGIN"))
        self.label_8.setText(_translate("Dialog", "userid"))
        self.label_9.setText(_translate("Dialog", "password"))
        self.pushButton_9.setText(_translate("Dialog", "LOGIN"))
        self.label_10.setText(_translate("Dialog", "if you dont have account then register first"))
        self.label_11.setText(_translate("Dialog", "pateint registration"))
        self.label_12.setText(_translate("Dialog", "first name"))
        self.label_13.setText(_translate("Dialog", "middle name"))
        self.label_14.setText(_translate("Dialog", "last name"))
        self.label_15.setText(_translate("Dialog", "mobile no"))
        self.label_16.setText(_translate("Dialog", "email id"))
        self.label_17.setText(_translate("Dialog", "DBO"))
        self.label_18.setText(_translate("Dialog", "address"))
        self.label_19.setText(_translate("Dialog", "pin code"))
        self.label_20.setText(_translate("Dialog", "email id"))
        self.pushButton_10.setText(_translate("Dialog", "register"))
        self.pushButton_11.setText(_translate("Dialog", "send OTP"))
        self.pushButton_12.setText(_translate("Dialog", "confurm"))
        self.label_21.setText(_translate("Dialog", "PATIENT DASHBORD"))
        self.pushButton_13.setText(_translate("Dialog", "book apointment"))
        self.pushButton_14.setText(_translate("Dialog", "doctors details"))
        self.pushButton_15.setText(_translate("Dialog", "past apointment"))
        self.pushButton_16.setText(_translate("Dialog", "ambulance call"))
        self.label_22.setText(_translate("Dialog", "fname"))
        self.label_23.setText(_translate("Dialog", "lname"))
        self.label_24.setText(_translate("Dialog", "mno"))
        self.label_49.setText(_translate("Dialog", "address"))
        self.label_50.setText(_translate("Dialog", "BOOK APOINTMENT"))
        self.pushButton_33.setText(_translate("Dialog", "DR.Vasant R Khnaolkar"))
        self.pushButton_34.setText(_translate("Dialog", "DR.Baba Amate"))
        self.pushButton_35.setText(_translate("Dialog", "DR.Dwarakanath S Kotnis"))
        self.pushButton_36.setText(_translate("Dialog", "DR.Anandibai Joshi"))
        self.label_51.setText(_translate("Dialog", "MD in tuberculosis. Nevertheless(USA)"))
        self.label_52.setText(_translate("Dialog", "Physician (University of mumbai )"))
        self.label_53.setText(_translate("Dialog", "MD in Pathology(London)"))
        self.label_54.setText(_translate("Dialog", "MD( Nagpur)"))
        self.label_59.setText(_translate("Dialog", "DR.Vasant R Khnaolkar"))
        self.label_60.setText(_translate("Dialog", "DR.Baba Amate"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
